services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: delong_test_2025
      MYSQL_DATABASE: delong
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3

  ipfs:
    image: ipfs/kubo:latest
    volumes:
      - ./data/ipfs:/root/.ipfs
    expose:
      - "5001"
      - "8080"
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      timeout: 10s
      retries: 3

  dstack-simulator:
    image: lilhammer/dstack-simulator:latest
    expose:
      - "8090"
    volumes:
      - ./data/simulator:/app/sockets

  delong:
    image: lilhammer/delong:latest
    env_file:
      - .env
    environment:
      - DSTACK_CLIENT_TYPE=dstack
      - IPFS_ADDR=/dns/ipfs/tcp/5001
      - ETH_HTTP_URL=${ETH_HTTP_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - CHAIN_ID=11155111
      - MYSQL_DSN=root:delong_test_2025@tcp(mysql:3306)/delong?charset=utf8mb4&parseTime=True&loc=Local
      - DSTACK_SIMULATOR_ENDPOINT=/app/sockets/dstack.sock
      - OFFICIAL_ACCOUNT_PRIVATE_KEY=${OFFICIAL_ACCOUNT_PRIVATE_KEY}
      - USE_JWT=true
      - JWT_SECRET=${JWT_SECRET}
      - SAMPLE_SRV_ADDR=http://delong-datapipe:8018
      - DIAGNOSTIC_SRV_ADDR=http://host.docker.internal:8008
    volumes:
      - ./data/delong_dataset:/data/delong_dataset
      - ./data/simulator:/app/sockets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_healthy
      delong-datapipe:
        condition: service_healthy
      dstack-simulator:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      retries: 3
      interval: 30s
    restart: no

  delong-datapipe:
    image: lilhammer/delong-pipeline:latest
    expose:
      - "8018"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8018/api/health"]
      timeout: 10s
      retries: 3
      interval: 30s
