services:
  alpine-ttypd:
    build: .
    image: hackinglab/alpine-ttyd-bash:3.2
    environment:
      - AUTHOR=e1
      - HL_USER_USERNAME=root
      - HL_USER_PASSWORD=123QWEasd
    ports:
      - 7681:7681
    volumes:
      - /:/host
    network_mode: host

  mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ipfs:
    image: ipfs/kubo:latest
    environment:
      IPFS_PATH: /data/ipfs
    volumes:
      - ipfs_staging_data:/data/ipfs
    expose:
      - "5001"
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      timeout: 10s
      retries: 5

  anvil:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc
    command: anvil --host 0.0.0.0 --port 8545 --state /data/anvil/delong_state.json
    volumes:
      - anvil_staging_data:/data/anvil
    expose:
      - "8545"
    healthcheck:
      test: ["CMD", "cast", "chain-id", "--rpc-url", "http://localhost:8545"]
      timeout: 30s
      retries: 10

  delong:
    image: lilhammer/delong:latest
    environment:
      APP_ENV: ${APP_ENV}
      IPFS_ADDR: ${IPFS_ADDR}
      ETH_HTTP_URL: ${ETH_HTTP_URL}
      ETH_WS_URL: ${ETH_WS_URL}
      CHAIN_ID: ${CHAIN_ID}
      DIAGNOSTIC_SRV_ENDPOINT: ${DIAGNOSTIC_SRV_ENDPOINT}
      MYSQL_DSN: ${MYSQL_DSN}
      OFFICIAL_ACCOUNT_PRIVATE_KEY: ${OFFICIAL_ACCOUNT_PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - dataset_staging_storage:/data/delong_dataset
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_healthy
      anvil:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
  ipfs_staging_data:
  anvil_staging_data:
  dataset_staging_storage:
