services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: delong_staging_2025
      MYSQL_DATABASE: delong_staging
    volumes:
      - mysql_staging_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    environment:
      IPFS_PATH: /data/ipfs
    volumes:
      - ipfs_staging_data:/data/ipfs
    expose:
      - "5001"
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      timeout: 10s
      retries: 5
    restart: unless-stopped

  anvil:
    image: aztecprotocol/foundry:25f24e677a6a32a62512ad4f561995589ac2c7dc
    command: anvil --host 0.0.0.0 --port 8545 --block-time 2 --state /data/anvil/delong_state.json
    volumes:
      - anvil_staging_data:/data/anvil
    expose:
      - "8545"
    healthcheck:
      test: ["CMD", "cast", "chain-id", "--rpc-url", "http://localhost:8545"]
      timeout: 30s
      retries: 10
    restart: unless-stopped

  delong:
    image: lilhammer/delong:latest
    environment:
      ENV: staging
      IPFS_ADDR: /ip4/ipfs/tcp/5001
      ETH_HTTP_URL: http://anvil:8545
      ETH_WS_URL: ws://anvil:8545
      CHAIN_ID: "31337"
      DIAGNOSTIC_SRV_ENDPOINT: ${DIAGNOSTIC_SRV_ENDPOINT}
      MYSQL_DSN: ${MYSQL_DSN}
      OFFICIAL_ACCOUNT_PRIVATE_KEY: ${OFFICIAL_ACCOUNT_PRIVATE_KEY}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - dataset_staging_storage:/data/delong_dataset
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      ipfs:
        condition: service_healthy
      anvil:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  mysql_staging_data:
  ipfs_staging_data:
  anvil_staging_data:
  dataset_staging_storage:

networks:
  default:
    name: delong_staging_network
